= disid-proof-ldap
Proof of Spring Boot app with LDAP authentication and groups and users management

== Requirements to provide in this proof

* [ ] Integrate the Spring LDAP related utilities:
** [X] Spring LDAP
** [ ] Spring Data LDAP
** [X] Spring Security LDAP

* [X] Provide authentication over an LDAP server using _Spring Security LDAP_

* [X] Provide authentication for an administrator user stored in the local database, which will have priority over any other user with the same id defined in the LDAP server.

* [X] Integrate and test with an embedded LDAP server for testing and also to be used with the _dev_ profile.

* [ ] Integrate and test with an external LDAP server for the default production profile (TODO: which external LDAP server to test?).

* [ ] Synchronization of groups data with the LDAP server.

* [ ] Synchronization of users data with the LDAP server.

* [ ] Groups CRUD stored in the LDAP server and additional information located in the local database.

* [ ] Users CRUD stored in the LDAP server and additional information located in the local database. This includes setting or updating the users password.

* [ ] Configurable properties to:
** [X] Connect to the LDAP server
** [X] Filter groups from the LDAP server
** [X] Filter users from the LDAP server
** [ ] Uniquely identification of single users
** [ ] Display users information

* [ ] Document the meaning and when to use the LDAP properties.

== Steps performed

=== Integrate LDAP authentication following the Spring guide

* Upgrade to Spring IO platform Brussels-SR4 to auto-run the embedded LDAP server.
* Add the properties to run the embedded LDAP server in the 'dev' profile:

[source,properties]
----
spring.ldap.embedded.ldif=classpath:test-server.ldif
spring.ldap.embedded.base-dn=dc=springframework,dc=org
spring.ldap.embedded.port=8389
----

* Add additional dependencies:

[source,xml]
----
  	<dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-security</artifactId>
    </dependency>
    <dependency>
        <groupId>org.springframework.ldap</groupId>
        <artifactId>spring-ldap-core</artifactId>
    </dependency>
    <dependency>
        <groupId>org.springframework.security</groupId>
        <artifactId>spring-security-ldap</artifactId>
    </dependency>
    <dependency>
        <groupId>com.unboundid</groupId>
        <artifactId>unboundid-ldapsdk</artifactId>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.springframework.security</groupId>
        <artifactId>spring-security-test</artifactId>
        <scope>test</scope>
    </dependency>
---- 

* Create _WebSecurityConfig_ class with the guide contents.

* Create _src/main/resources/test-server.ldif_ file with the guide contents.

* Create _SecurityIT_ class for integration testing. Make it run with the _dev_ profile.

=== Test multiple authentication method support

* Test multiple authentication method support for the local administrator user in memory, by updating the _WebSecurityConfig_ class with:

[source,java]
----
  public void configure( AuthenticationManagerBuilder auth ) throws Exception
  {

    // To have many authentication options, just add them to the AuthenticationManagerBuilder in
    // the order to be checked

    auth.inMemoryAuthentication().withUser( "user" ).password( "password" ).roles( "USER" ).and().withUser( "admin" )
        .password( "password" ).roles( "USER", "ADMIN" );

    auth.ldapAuthentication().userDnPatterns( "uid={0},ou=people" ).groupSearchBase( "ou=groups" )
        .contextSource( contextSource() ).passwordCompare().passwordEncoder( new LdapShaPasswordEncoder() )
        .passwordAttribute( "userPassword" );
  }
----

=== Add support to store the local administrator user in the application database

* Create a new entity (_AdminUser_) to store the administration user password.

* Generate related repository and service. Add new method to the repository:

[source,java]
----
AdminUser findByLogin( String login );
----

* Create the _AdminUserDetails_ class.

* Make the _AdminUserService_ implement _UserDetailsService_.

* Replace in memory authentication with a _DaoAuthenticationProvider_ using the _AdminUserService_ in the _WebSecurityConfig_.

=== Make the LDAP connection configurable

* Create a _LdapProperties_ class annotated with _@ConfigurationProperties_.
* Create a _LdapConfiguration_ class to initialize the _DefaultSpringSecurityContextSource_ from the _LdapProperties_.
* Remove the creation of the ldap context in _WebSecurityConfig_.

=== Make LDAP authentication properties configurable

* Add additional properties to _LdapProperties_ and the _application*.properties_ files.
* Use the _LdapProperties_ component in the _WebSecurityConfiguration_ in the configuration of the LDAP authentication.

== Reference documentation

* "Spring guide: Authenticating a User with LDAP":https://spring.io/guides/gs/authenticating-ldap/ 

